import "./globals.css";
import { Mona_Sans } from "next/font/google";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const mona = Mona_Sans({
  subsets:["latin"],
})


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
         className={`${mona.className} `}
      >
        {children}
      </body>
    </html>
  );
}
